ن يمف عنهاخ زة ، ف[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_API_URL = "https://haymanh-backend.vercel.app"
